name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 5.5

      - name: Format Timezone to UTC +5:30
        run: |
          find profile-summary-card-output -type f -name "4-productive-time.svg" -exec sed -i 's/(UTC +5.50)/(UTC +5:30)/g' {} +

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(summary-cards): update profile summary cards"
            git push
          fi
